---
title: "HW06"
author: "Danika"
format: pdf
---

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

# This is the input code
x <- "4AKE"
a <- read.pdb(x)


s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

a.chainA <- trim.pdb(a, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

a.b <- a.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

plotb3(a.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```

# Should read any protein PDB data and outputs a plot
```{r}
library(bio3d)
x <- "4AKE"

newfunction <- function(x){
  a <- read.pdb(x)
  a.chainA <- trim.pdb(a, chain="A", elety="CA")
  a.b <- a.chainA$atom$b
  plotb3(a.b, sse=s3.chainA, typ="l", ylab="Bfactor")
}

newfunction(x)
```

```{r}
newfunction("1AKE")
```

```{r}
newfunction("1E4Y")
```


# The graphs are the output







